name: Claude Assistant
permissions:
  contents: write
  pull-requests: read
  issues: write
  id-token: write
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
jobs:
  claude-response:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1
      - uses: anthropics/claude-code-action@v1.0.1
        with:
          use_bedrock: "true"
          claude_args: |
            --model ${{ secrets.AWS_CLAUDE_PROFILE }}
            --max-turns 15
            --system-prompt "全て日本語で回答してください"
