name: Claude Assistant
permissions:
  contents: write
  pull-requests: read
  issues: write
  id-token: write
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
jobs:
  claude-response:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 30
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1
      - uses: anthropics/claude-code-action@v1.0.1
        timeout-minutes: 1
        with:
          use_bedrock: "true"
          claude_args: |
            --model ${{ secrets.AWS_CLAUDE_PROFILE }}
            --max-turns 20
            --system-prompt  |
              全て日本語で回答してください。
              
              以下のルールに従ってください：
              - コードレビューの際は具体的な改善提案を含める
              - セキュリティに関する問題があれば必ず指摘する
              - パフォーマンスの観点からも評価する
              - 可読性とメンテナンス性を重視する
